resources:
  repositories:
  - repository: tox
    type: github
    endpoint: ngrewe
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2
jobs:
- template: run-tox-env.yml@tox
  parameters:
    tox_version: 'tox'
    jobs:
      py37_black:
        image: [linux]
      py38:
        image: [linux]
      py37:
        image: [linux]
      py36:
        image: [linux]