resources:
  repositories:
  - repository: tox
    type: github
    endpoint: ngrewe
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2
jobs:
- template: run-tox-env.yml@tox
  parameters:
    tox_version: 'tox'
    jobs:
      py37_black:
        image: [linux]
      py38:
        image: [linux]
      py37:
        image: [linux]
      py36:
        image: [linux]
    coverage:
      with_toxenv: 'coverage'
      for_envs: [py38, py37, py36]
- job: docker_image
  displayName: Build Docker Image
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    imageName: 'glaux/vault-ssh-renew'
  steps:
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        repository: $(imageName)
        command: build
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: glaux-registry
        Dockerfile: Dockerfile