apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ssh-config
  labels:
    app.kubernetes.io/part-of: 'vault-ssh-renew'
data:
  VAULT_ADDR: http://127.0.0.1:8200
  VAULT_SSH_SIGN_PATH: ssh/sign/host